// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFacEeb6UU2ysMkN9JqkGbcXqTskuUn4E',
    appId: '1:316928106040:web:86c97b4459610a1fee10cd',
    messagingSenderId: '316928106040',
    projectId: 'social-media-app-auth-6ffb2',
    authDomain: 'social-media-app-auth-6ffb2.firebaseapp.com',
    storageBucket: 'social-media-app-auth-6ffb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcCci2hG1OaTmsM7yYZlf-2LDPBesqUYY',
    appId: '1:316928106040:android:88194e32ff0e08a3ee10cd',
    messagingSenderId: '316928106040',
    projectId: 'social-media-app-auth-6ffb2',
    storageBucket: 'social-media-app-auth-6ffb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgf7EXIly7L4En10PLCjcP8YjjuptKX2Y',
    appId: '1:316928106040:ios:0621eb7bb55a1076ee10cd',
    messagingSenderId: '316928106040',
    projectId: 'social-media-app-auth-6ffb2',
    storageBucket: 'social-media-app-auth-6ffb2.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgf7EXIly7L4En10PLCjcP8YjjuptKX2Y',
    appId: '1:316928106040:ios:0621eb7bb55a1076ee10cd',
    messagingSenderId: '316928106040',
    projectId: 'social-media-app-auth-6ffb2',
    storageBucket: 'social-media-app-auth-6ffb2.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFacEeb6UU2ysMkN9JqkGbcXqTskuUn4E',
    appId: '1:316928106040:web:95b5cc2a645020aeee10cd',
    messagingSenderId: '316928106040',
    projectId: 'social-media-app-auth-6ffb2',
    authDomain: 'social-media-app-auth-6ffb2.firebaseapp.com',
    storageBucket: 'social-media-app-auth-6ffb2.firebasestorage.app',
  );
}
